### ISSUE TITLE
LSLEditorCE v3 porting TODO list

### ISSUE THREAD

**Issue by jojorne** [LSLEditor/LSLEditorCE#13]
LSLEditorCE v3 porting TODO list

The aim of this overhaul of the code-base is to make it multi-platform friendly and gain a better insight into the workings of all areas of the code. Hopefully this will lead to removal of any cruft and a leaner code-base.

- [ ] Port window UI/control to GTK+;
- [ ] Port 'syntax' stuff to .Net Core;
- [ ] Clean up all the 'syntax' stuff. Alphabetise all constants, events, functions, etc.).

PS.: Updating the list as we go.

**Comment by niel** [comment]
Yeah, currently the app uses a bunch of PInvokes for mouse and similar access from the system libraries. AFAIK Linux has no direct equivalent, but I think I saw that GTK has something we can use for cross-platform.

**Comment by jojorne** [comment]
OK, MonoDevelop complains about the path to the files in the resources.
It just happens to be case sensitive...
Also appears that there is no "v7.0A\bin\RC.exe" in linux... does it?

**Comment by niel** [comment]
OK. 
Remove the RC.exe as I'm pretty certain it is a windows only thing.
"AssemblyRevisionIncrementer.exe" will probably need to be replaced any way for multi-platform.
